version: '3'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Ep2uU9ytumP1"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  
  asc-app:
    build: .
    ports:
      - "8090:80"