version: '3'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Ep2uU9ytumP1"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  
  asc-app:
    environment:
      SA_PASSWORD: "Ep2uU9ytumP1"
      SERVER_NAME: "sql-server"
      PWD_HASH: "15"
      TOKEN_HASH: "9b521e8c7da3fe2d6624ed7c9c7401416c62faf24c511916042d761f80d354dd"
    build: .
    ports:
      - "8090:80"

  frontend:
    image: aquilams/asctestfrontend
    ports:
      - "4200:4200"